version: "3.9"

services:
  app:
    container_name: app
    build: 
      context: "./app"
      dockerfile: Dockerfile
    environment:
      - "APP_PORT=8080"
      - "MODE=local"
    ports:
      - "8080:8080"
