version: "3.9"

networks: 
  network_example:
    name: network_example
    driver: bridge


services: 
  mongodb-example:
    image: mongo:latest
    container_name: mongodb-network
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: fauzan
      MONGO_INITDB_ROOT_PASSWORD: fauzan
      MONGO_INITDB_DATABASE: admin
    networks:
      - network_example
